
project_id = "oygmfedzibzxojqirgxo"

[functions.gupshup-webhook]
verify_jwt = false

[functions.send-gupshup-notification]
verify_jwt = true

[functions.employee-onboarding]
verify_jwt = false

[functions.verify-employee-code]
verify_jwt = false
